name: Build and Push Docker Image

on:
  push:
    branches:
      - main     # Only trigger on pushes to the main branch
  pull_request:
    branches:
      - main     # Optionally, run on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout source code
        uses: actions/checkout@v3

      # Set up Docker Buildx for advanced build features
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Cache Docker layers to speed up subsequent builds
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and tag the Docker image with both the commit hash and 'latest' tag
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile              # Path to the Dockerfile
          push: true                      # Push the image to the registry
          tags: |
            ghcr.io/${{ github.repository_owner }}/erp-demo:latest   # Tag as latest
            ghcr.io/${{ github.repository_owner }}/erp-demo:${{ github.sha }} # Tag with full commit hash
            ghcr.io/${{ github.repository_owner }}/erp-demo:${{ github.sha.substring(0, 7) }} # Tag with short commit hash
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/erp-demo:latest
          cache-to: type=inline

      # Optionally, you can add steps for testing or scanning the built image for security issues:
      # Example: Image vulnerability scan (Trivy, Snyk, etc.)
      # Example: Run tests on the built image
